oop_2/week_2/catalog/urls.py
from django.urls import path
from . import views
from django.urls import re_path as url
from .models import Application

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^application/$', views.ApplicationList.as_view(), name='application'),
    url(r'^application/create/$', views.ApplicationCreate.as_view(), name='application-create'),
    url(r'^application/(?P<pk>\d+)/delete/$', views.ApplicationDelete.as_view(), name='application-delete'),
    path(r'^application/(?P<pk>\w+)/(?P<st>\w+)/update/$', views.confirm_update, name='confirm-update'),
    url(r'^application/application_admin/$', views.ApplicationListAdmin.as_view(), name='application-admin'),
    path('view_categories', views.ViewCategory.as_view(), name='view-categories'),
    path('view_categories/create_category', views.CreateCategory.as_view(), name='create-category'),
    url(r'^category/(?P<pk>\d+)/delete/$', views.DeleteCategory.as_view(), name='delete-category'),
]

oop_2/week_2/week_2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('catalog/', include('catalog.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oop_2/week_2/catalog/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin, AbstractBaseUser, BaseUserManager
import datetime
from django.urls import reverse
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
import uuid

def validate_image(fieldfile_obj):
    filesize = fieldfile_obj.file.size
    megabyte_limit = 2.0
    if filesize > megabyte_limit * 1024 * 1024:
        raise ValidationError("Максимальный размер файла %sMB" % str(megabyte_limit))

class CustomAccountManager(BaseUserManager):
    def create_user(self, username, fullname, email, password):
        user = self.model(email=email, username=username, fullname=fullname, password=password)
        user.set_password(password)
        user.is_staff = False
        user.is_superuser = False
        user.save(using=self._db)
        return user

    def create_superuser(self, username, fullname, email, password):
        if not email:
            raise ValueError("User must have an email")
        if not password:
            raise ValueError("User must have a password")
        if not fullname:
            raise ValueError("User must have a full name")
        user = self.model(email=email, username=username, fullname=fullname, password=password)
        user.set_password(password)
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

    def get_by_natural_key(self, username_):
        return self.get(username=username_)

class AdvUser(AbstractBaseUser, PermissionsMixin):
    id = models.AutoField(primary_key=True, unique=True)
    username = models.CharField(max_length=200, unique=True, verbose_name='Логин')
    fullname = models.CharField(max_length=200)
    email = models.EmailField(unique=True, max_length=200)
    is_staff = models.BooleanField(default=False)
    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['fullname', 'password', 'email',]

    objects = CustomAccountManager()

    def get_short_name(self):
        return self.username

    def natural_key(self):
        return self.username

    def __str__(self):
        return self.username

class Category(models.Model):
    name = models.CharField(max_length=200, help_text='Введите категорию заявки', verbose_name='Название категории')

    def __str__(self):
        return self.name

class Application(models.Model):
    name = models.CharField(max_length=200, help_text='Введите название заявки', verbose_name='Название заявки')
    summary = models.CharField(max_length=1000, help_text='Введите описание заявки', verbose_name='Описание заявки')
    category = models.ForeignKey('Category', help_text='Выберите категория для заявки', on_delete=models.SET_NULL, null=True, verbose_name='Категория заявки')
    timestamp = models.DateTimeField(default=timezone.now())
    image = models.ImageField(upload_to='images/', validators=[validate_image], help_text='Максимальный размер '
                                                                                          'изображения 2MB', verbose_name='Пример дизайна')

    application_status = (
        ('Новая', 'Новая',),
        ('Принято в работу', 'Принято в работу',),
        ('Выполнено', 'Выполнено',)
    )

    status = models.CharField(max_length=50, choices=application_status, blank=True, default='Новая', verbose_name='Статус заявки')
    client = models.ForeignKey(AdvUser, on_delete=models.SET_NULL, null=True, blank=True, to_field='id')
    comment = models.TextField(max_length=500, blank=True, verbose_name='Комментарий')
    design = models.ImageField(upload_to='images/',
                               help_text="Максимальный размер изображения 2MB",
                               blank=True,
                               null=True,
                               validators=[validate_image], verbose_name='Фото готового дизайна:')
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('profile')

oop_2/week_2/catalog/forms.py
from django.contrib.auth.models import User
from django import forms
from django.core.validators import RegexValidator
from django.contrib.auth import password_validation

from catalog.models import AdvUser, Application, Category
from django.core.exceptions import ValidationError


class UserRegistrationForm(forms.ModelForm):
    LetterValidator = RegexValidator(r'^[- а-яА-Я]*$')
    LoginValidator = RegexValidator(r'^[- a-zA-Z]*$')
    username = forms.CharField(validators=[LoginValidator], required=True, label='Логин',
                               help_text='Только латиница и дефис, уникальный')
    fullname = forms.CharField(validators=[LetterValidator], required=True, label='ФИО',
                               help_text='Только кириллические буквы, дефис и пробелы')
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)
    consent = forms.BooleanField(widget=forms.CheckboxInput, required=True,
                                 label='Согласие на обработку персональных данных')

    class Meta:
        model = AdvUser
        fields = ('username', 'fullname', 'email', 'password', 'password2', 'consent')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Пароли не совпадают.')
        return cd['password2']

    def clean_password1(self):
        password = self.cleaned_data['password']
        if password:
            password_validation.validate_password(password)
        return password


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['name', 'summary', 'category', 'image']


class ApplicationDesignForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['design']


class ApplicationCommentForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['comment']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

oop_2/week_2/catalog/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import UserRegistrationForm, ApplicationForm, ApplicationCommentForm, ApplicationDesignForm, CategoryForm
from django.views import generic
from .models import Application, AdvUser, Category
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .filters import ApplicationFilter
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import PermissionRequiredMixin

# Create your views here.

def home(request):
    num_applications_in_progress = Application.objects.all().filter(status='Принято в работу').count()
    applications_done = Application.objects.filter(status='Выполнено')

    return render(request, 'home.html', context={'num_applications_in_progress': num_applications_in_progress,
                                                  'applications_done': applications_done})

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'catalog/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'catalog/register.html', {'user_form': user_form})


@login_required()
def profile(request):
    return render(request, 'catalog/profile.html')

class ApplicationList(LoginRequiredMixin, generic.ListView):
    model = Application
    template_name = 'catalog/application_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = ApplicationFilter(self.request.GET, queryset=self.get_queryset())
        return context

    def get_queryset(self):
        return Application.objects.filter(client=self.request.user.id)

class ApplicationListAdmin(LoginRequiredMixin, generic.ListView):
    model = Application
    template_name = 'catalog/application_list_admin.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = ApplicationFilter(self.request.GET, queryset=self.get_queryset())
        return context

class ApplicationCreate(CreateView):
    model = Application
    form_class = ApplicationForm
    template_name = 'application_form.html'
    success_url = reverse_lazy('application')

    def form_valid(self, form):
        fields = form.save(commit=False)
        fields.client = self.request.user
        fields.save()
        return super().form_valid(form)

class ApplicationDelete(DeleteView):
    model = Application
    success_url = reverse_lazy('application')

def confirm_update(request, pk, st):
    newApplication = Application.objects.get(id=pk)
    newApplication.save()

    if st == 'Выполнено':
        if request.method == 'POST':
            form = ApplicationDesignForm(request.POST, request.FILES)
            if form.is_valid():
                newApplication.design = form.cleaned_data['design']
                newApplication.status = st
                newApplication.save()
                return redirect('application-admin')
        else:
            form = ApplicationDesignForm()
        return render(request, 'catalog/update_application.html', {'form': form})

    if st == 'Принято в работу':
        if request.method == 'POST':
            form = ApplicationCommentForm(request.POST, request.FILES)
            if form.is_valid():
                newApplication.comment = form.cleaned_data['comment']
                newApplication.status = st
                newApplication.save()
                return redirect('application-admin')
        else:
            form = ApplicationCommentForm()
        return render(request, 'catalog/update_application.html', {'form': form})

class ViewCategory(LoginRequiredMixin, generic.ListView):
    model = Category
    template_name = 'catalog/categories_list.html'
    context_object_name = 'categories_list'

class CreateCategory(CreateView):
    template_name = 'catalog/category_create.html'
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('view-categories')

class DeleteCategory(LoginRequiredMixin, DeleteView):
    model = Category
    success_url = reverse_lazy('view-categories')

oop_2/week_2/catalog/templates/catalog/application_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1 class="text-danger">Удаление заявки</h1>

    <p>Вы уверены, что хотите удалить заявку: {{application}}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="Да, удалить."/>
    </form>
</div>
{% endblock %}

oop_2/week_2/catalog/templates/catalog/application_list.html
{% extends "base.html" %}
{% load bootstrap %}
{% block content %}
<div class="container">
    <h1 class="text-success">Мои заявки</h1>
    <h3 class="text-success">Сортировка заявок по статусу:</h3>
    <form action="" method="GET">
        {{ filter.form|bootstrap }}
        <button class="btn btn-success" type="submit" class="btn btn-primary">Показать</button>
    </form>
    {% if application_list %}
    <ul>
        {% for application in filter.qs %}
        <li>Пользователь: {{application.client}}</li>
        <li>Название заявки: {{application.name}}</li>
        <li>Описание заявки: {{application.summary}}</li>
        <li>Категория заявки: {{application.category}}</li>
        <li>Временная метка: {{application.timestamp}}</li>
        <li>Статус заявки: {{application.status}}</li>
        {% if application.status == "Принято в работу" %}
        <li>Комментарий: {{application.comment}}</li>
        {% elif application.status == "Выполнено" %}
        <img width="200px" height="100px" src="{{ application.design.url }}">
        {% endif %}
        <li><a class="text-danger" href="{% url 'application-delete' application.pk %}">Удалить заявку</a></li>
        <br>
        <br>
        <br>
        {% endfor %}
    </ul>
    {% else %}
    <p>Нет заявок.</p>

    {% endif %}
</div>
{% endblock %}

oop_2/week_2/catalog/templates/catalog/application_list_admin.html
{% extends "base.html" %}
{% load bootstrap %}
{% block content %}
<div class="container">
    {% if perms.catalog.change_application %}
    <h1 class="text-success">Заявки всех пользователей</h1>
    <h3 class="text-success">Сортировка заявок по статусу:</h3>
    <form action="" method="GET">
        {{ filter.form|bootstrap }}
        <button class="btn btn-success" type="submit" class="btn btn-primary">Показать</button>
    </form>
    {% if application_list %}
    <ul>
        {% for application in filter.qs %}
        <li>Пользователь: {{application.client}}</li>
        <li>Название заявки: {{application.name}}</li>
        <li>Описание заявки: {{application.summary}}</li>
        <li>Категория заявки: {{application.category}}</li>
        <li>Временная метка: {{application.timestamp}}</li>
        <li>Статус заявки: {{application.status}}</li>
        <div>
            <h4 class="text-success">Изменение Статуса:</h4>
            <a class="text-success" href="{% url 'confirm-update' application.pk 'Принято в работу' %}">Статус - принято
                в работу</a>
            <a class="text-success" href="{% url 'confirm-update' application.pk  'Выполнено' %}">Статус - выполнено</a>
        </div>
        <li><a class="text-danger" href="{% url 'application-delete' application.pk %}">Удалить заявку</a></li>
        <br>
        <br>
        <br>
        {% endfor %}
    </ul>
    {% else %}
    <p>Нет заявок.</p>
    {% endif %}
    {% endif %}
</div>
{% endblock %}

oop_2/week_2/catalog/templates/catalog/categories_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div>
        <h1 class="text-success">Управление категориями</h1>
        <a class="text-success" href="{% url 'create-category' %}">Добавить новую категорию</a>
    </div>

    {% if categories_list %}
    <h2 class="text-danger">Удалить категории</h2>
    {% for category in categories_list %}
    <p>
        {{ category.name }} -
        <a class="text-danger" href="{% url 'delete-category' category.pk %}">удалить</a>
    </p>
    {% endfor %}
    {% else %}
    <p>Не существует категорий заявок</p>
    {% endif %}
</div>
{% endblock %}

oop_2/week_2/catalog/templates/catalog/category_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div>
        <h1 class="text-danger">Удаление категории</h1>
        <p>Вы уверены, что хотите удалить категорию: {{category}}?</p>
        <form method="post">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">Да, удалить</button>
        </form>
    </div>
</div>
{% endblock %}

oop_2/week_2/catalog/templates/catalog/category_create.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div>
    <h1 class="text-success">Создать категорию</h1>
    <form method="post">
      {{form.as_p}}
      {% csrf_token %}
      <button class="btn btn-success" type="submit">Добавить</button>
    </form>
  </div>
</div>
{% endblock %}

oop_2/week_2/catalog/templates/catalog/profile.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <ul>
        <li><a class="text-success" href="{% url 'application' %}">Мои заявки</a></li>
        {% if perms.catalog.change_application %}
        <li><a class="text-success" href="{% url 'view-categories' %}">Управление категориями</a>
        <li><a class="text-success" href="{% url 'application-admin' %}">Заявки всех пользователей</a></li>
        {% endif %}
        <li><a class="text-success" href="{% url 'application-create' %}">Создать заявку</a></li>
    </ul>
</div>
{% endblock %}

oop_2/week_2/catalog/templates/catalog/register.html
{% extends "base.html" %}
{% block content %}

<div class="container d-flex justify-content-center">
    <div>
    <h1 class="text-success">Создание аккаунта</h1>
    <p>Зарегистрируйтесь, следуя этой форме:</p>
    <form action="." method="post">
        {{ user_form.as_p }}
        {% csrf_token %}
        <p><input class="btn btn-success" type="submit" value="Создать аккаунт"></p>
    </form>
        </div>
</div>
{% endblock %}

oop_2/week_2/catalog/templates/catalog/register_done.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1 class="text-success" >Здравствуйте {{ new_user.first_name }}!</h1>
    <p>Ваш аккаунт успешно создан. Вы можете <a class="text-success" href="{% url 'login' %}">войти</a>.</p>
</div>
{% endblock %}

oop_2/week_2/catalog/templates/catalog/update_application.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div>
        <h1 class="text-success">Изменение статуса</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <br>
            <button class="btn btn-success" type="submit">Добавить</button>
        </form>
    </div>
</div>
{% endblock %}